name: easimage_lib
description: "Libraries of project easyimage"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  image: ^4.2.0
  http: ^1.2.2
  xml: ^6.5.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8